import {Dimensions, StyleSheet} from 'react-native';
import colors from '../constants/colors';
import fonts from '../constants/fonts';
import {moderateScale, verticalScale} from '../helpers/ResponsiveFonts';
import {
  responsiveFontSize,
  responsiveHeight,
  responsiveWidth,
} from 'react-native-responsive-dimensions';
import {
  Border,
  Color,
  FontFamily,
  FontSize,
  Padding,
} from '../globelstyle/globelstyle';

const styles = StyleSheet.create({
  janeTypo: {
    fontFamily: 'DMSerifDisplay-Regular',
    textAlign: 'left',
    color: '#ffecd1',
  },
  frameWrapperBorder: {
    borderColor: '#ffecd1',
    borderStyle: 'solid',
    flexDirection: 'row',
    // position: 'absolute',
  },
  socialIconsLayout: {
    height: 48,
    width: 48,
    // marginLeft: 23,
  },
  editProfileTypo: {
    fontFamily: FontFamily.dMSansRegular,
    // fontFamily: 'DMSerifDisplay-Regular',
    fontSize: 16,
  },
  vectorIconLayout: {
    height: 3,
    maxWidth: '100%',
    // borderRadius: Border.br_4xs,
    overflow: 'hidden',
    flex: 1,
  },
  vectorGroupFlexBox: {
    width: Dimensions.get('window').width / 1.2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingHorizontal: 15,
  },
  socialLayout: {
    // marginLeft: 23,
    height: 48,
    width: 48,
    overflow: 'hidden',
  },
  dlF45312434Layout: {
    lineHeight: responsiveHeight(4),
    color: '#ffecd1',
  },
  frameChild: {
    // top: 9,
    // left: 0,
    width: responsiveWidth(2.5),
    height: responsiveHeight(4),
    // marginTop: 10,
    // position: 'absolute',
  },
  safeStop: {
    top: -responsiveHeight(0.5),
    left: responsiveWidth(2),
    fontSize: responsiveFontSize(5),
    color: Color.teal,
    textAlign: 'left',
    // position: 'absolute',
  },
  frameParent: {
    alignItems: 'center',
    flexDirection: 'row',
    marginVertical: responsiveHeight(5),
    // flex: 0.2,
    // width: responsiveWidth(42),
    // height: responsiveHeight(5),
  },
  frameItem: {
    top: 49,
    left: -16,
    borderRadius: 18,
    width: 745,
    height: 709,
    position: 'absolute',
  },
  frameInner: {
    marginTop: responsiveHeight(-10),
    // lefT: responsiveWidth(0.2),
    width: responsiveWidth(63),
    height: responsiveHeight(30),
    // borderRadius: responsiveWidth(100),
    // position: 'absolute',
  },
  cameraAltIcon: {
    width: responsiveWidth(8),
    height: responsiveHeight(4),
    overflow: 'hidden',
  },
  cameraAltWrapper: {
    backgroundColor: Color.teal,
    justifyContent: 'center',
    flexDirection: 'row',
    borderRadius: responsiveWidth(6),
    alignItems: 'center',
  },
  frameWrapper: {
    top: responsiveHeight(29),
    left: responsiveWidth(47.4),
    borderWidth: 7.2,
    flexDirection: 'row',
    borderRadius: responsiveWidth(10),
  },
  ellipseParent: {
    // marginTop: -30,
    // width: 280,
    // height: 280,
    alignSelf: 'center',
    // position: 'absolute',
    // backgroundColor: '#78290F',
    // borderRadius: responsiveWidth(50),
  },
  shareSafeStop: {
    marginLeft: responsiveWidth(8),
    textAlign: 'center',
    color: '#ffecd1',
    // top: responsiveHeight(1),
  },
  frameChild1: {
    marginLeft: 13,
  },
  socialIcons: {
    overflow: 'hidden',
  },
  socialIcons2: {
    display: 'none',
  },
  socialIconsParent: {
    borderRadius: 60,
    // paddingHorizontal: 0,
    paddingVertical: responsiveHeight(2),
    marginTop: responsiveHeight(3.5),
    // justifyContent: 'center',
    backgroundColor: '#ffecd1',
    // width: 324,
  },
  frameGroup: {
    // marginLeft: responsiveWidth(-41),
    // top: responsiveHeight(35),
    // left: '50%',
    // position: 'absolute',
    alignItems: 'center',
  },
  jane: {
    fontSize: 30,
    lineHeight: 54,
    color: '#78290F',
    textAlign: 'left',
  },
  text: {
    fontSize: 31,
  },
  smith1: {
    fontSize: 32,
    lineHeight: 36,
  },
  smith: {
    color: '#78290F',
    textAlign: 'left',
  },
  janeParent: {
    justifyContent: 'center',
    alignItems: 'flex-end',
    flexDirection: 'row',
  },
  dlF45312434: {
    fontSize: responsiveFontSize(2.5),
    fontWeight: '500',
    fontFamily: 'DMSerifDisplay-Regular',
    textAlign: 'center',
    color: '#78290F',
  },
  dlF45312434Wrapper: {
    marginTop: responsiveHeight(0.2),
    flexDirection: 'row',
    alignItems: 'center',
  },
  frameContainer: {
    // marginLeft: responsiveWidth(-28),
    // flex: 1,
    // top: responsiveWidth(60),
    // width: responsiveWidth(60),
    // left: responsiveWidth(43.8),
    // position: 'absolute',
    flex: 1,
    alignItems: 'center',
  },
  icon: {
    width: 16,
    height: 16,
  },
  systemIconsedit: {
    // width: responsiveWidth(8),
    // height: responsiveHeight(1),
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
  },
  editProfile: {
    fontFamily: FontFamily.dMSansRegular,
    textAlign: 'left',
    fontSize: responsiveFontSize(2),
    color: '#78290F',
    paddingLeft: responsiveHeight(1.5),
  },
  systemIconseditParent: {
    // marginLeft: responsiveWidth(-18),
    marginTop: responsiveHeight(2),
    borderRadius: 68,
    borderWidth: 1.5,
    paddingHorizontal: Padding.p_base,
    paddingVertical: 4,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
  },
  vectorParent: {
    // alignSelf: 'stretch',
    // height: responsiveHeight(85),
    marginTop: 34,
    flex: 1,
  },
  home: {
    // width: responsiveWidth(100),
    // height: responsiveHeight(70),
    // paddingHorizontal: Padding.p_base,
    // paddingTop: responsiveHeight(10),
    // justifyContent: 'flex-end',
    alignItems: 'center',
    // overflow: 'hidden',
    flex: 1,
    backgroundColor: '#FFECD1',
  },
  new: {
    textAlign: 'center',
    marginLeft: 31,
  },
  titleSheet: {
    // top: responsiveHeight(2),
    // left: 17,
    fontSize: responsiveFontSize(5),
    textAlign: 'left',
    fontWeight: '500',

    fontFamily: 'DMSerifDisplay-Regular',
  },
  emailClr: {
    color: Color.teal,
    textAlign: 'left',
  },
  b1324801Wrapper: {
    borderStyle: 'solid',
    borderColor: '#15616d',
    borderWidth: 2,
    color: '#15616d',
    fontSize: 18,
  },
  wrapperFlexBox: {
    alignItems: 'center',
    padding: 12,
    width: responsiveWidth(80),
    borderRadius: Border.br_5xs,
    flexDirection: 'row',
    overflow: 'hidden',
  },
  signUp1: {
    fontSize: FontSize.size_xl,
    color: '#fff',
    textAlign: 'left',
    fontFamily: 'DMSerifDisplay-italic',
  },
  signUpWrapper: {
    backgroundColor: Color.teal,
    justifyContent: 'center',
    marginTop: 5,
  },
  badgeNumber: {
    // fontSize: FontSize.size_sm,
    lineHeight: responsiveHeight(2.5),
    textAlign: 'left',
    fontFamily: FontFamily.dMSansRegular,
    fontWeight: '700',
    marginVertical: 5,
  },
  loginHereClr: {
    color: Color.teal,
    textAlign: 'left',
  },
  emailParent: {
    marginTop: responsiveHeight(-1),
  },
  loginWrapper: {
    backgroundColor: Color.teal,
    justifyContent: 'center',
    // marginTop: responsiveHeight(0.5),
  },
  login1: {
    fontSize: responsiveFontSize(2),
    color: '#FFECD1',
    textAlign: 'left',
    fontFamily: FontFamily.dMSansBold,
    fontWeight: '500',
  },
  imagecontainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    opacity: 0.7,
    // backgroundColor: 'black',
    justifyContent: 'center',
    alignItems: 'center',
  },
});

export default styles;
